# /// script
# dependencies = [
#   "pydantic",
#   "langchain[openai]",
#   "requests",
# ]
# ///

from langchain_openai import ChatOpenAI

from langchain_core.messages import HumanMessage, SystemMessage

from pydantic import BaseModel, Field

import base64
from pathlib import Path

import os
import time
import requests
import subprocess

ITER_NO = 20

class Animal(BaseModel):
    species: str = Field(description="The species of the animal")
    breed: str = Field(description="The breed of the animal")
    features: list[str] = Field(description="List of features used in classification")

SYSTEM = SystemMessage(
    "You are an expert animal recognition AI. Your task is to analyze images and accurately identify the species (e.g., dog, cat, bird) and, when possible, the specific breed (e.g., Golden Retriever, Siamese, Persian). If the breed is unclear, provide the most likely options or state that the breed is unknown. Be precise, use common breed names, and note any distinctive physical features that support your classification."  # generated by chatgpt
)

def main1():

    print("HELLLLOOOOO")

    model_name = os.environ.get("CLIENT_TYPE", "Cannot Find Model Name")
    host = os.environ.get("OLLAMA_HOST", "Cannot Find Host")

    model = ChatOpenAI(
        model_name=model_name,
        temperature=0,
        openai_api_base=f"{host}/v1",
        openai_api_key="dummy",
    ) # .with_structured_output(Animal)

    for _ in range(ITER_NO):
        r = requests.get('https://cataas.com/cat')
        r.raise_for_status()
        print(
            model.invoke(
                [
                    SYSTEM,
                    HumanMessage(
                        content=[
                            {
                                "type": "text",
                                "text": "Describe the breed and species of the animal in this image, return as JSON",
                            },
                            {
                                "type": "image",
                                "source_type": "base64",
                                "data": base64.b64encode(r.content).decode(),
                                "mime_type": "image/jpeg",
                            },
                        ]
                    ),
                ]
            )
        )

def main():

    print("HELLLLOOOOO")

    model_name = os.environ.get("CLIENT_TYPE", "Cannot Find Model Name")

    while subprocess.run(["ollama", "list"], capture_output=True).returncode != 0:
        time.sleep(5)

    prompt = ["ollama", "run", model_name, "'What breed of cat is in /tmp/cat.jpg and does the cat look dangerous?'"]

    for _ in range(ITER_NO):
        subprocess.run(["curl", "https://cataas.com/cat", "-o", "/tmp/cat.jpg"])
        #subprocess.run(["img2sixel", "/tmp/cat.jpg"])
        subprocess.run(prompt)

if __name__ == "__main__":
    main()