FROM ollama/ollama:latest
RUN apt-get update && apt-get install -y curl
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY parking_signs /app/parking_signs
COPY client.py /app/client.py
ENTRYPOINT ["sh", "-c", "uv run /app/client.py"]