global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.containers.internal:9100']

    # metric_relabel_configs:
    #   - source_labels: [__name__]
    #     regex: 'integrated_power_mW'
    #     target_label: __name__
    #     replacement: 'consumed power'
    

  - job_name: ollama
    static_configs:
      - targets: ['ollama-stats:9882']

remote_write:
  - url: 'http://host.containers.internal:9090/api/v1/write'