global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.containers.internal:9100']
  
  - job_name: 'jetson-node'
    static_configs:
      - targets: ['jetson_stats_node_exporter:9100']

  - job_name: ollama
    static_configs:
      - targets: ['ollama-stats:9882']

remote_write:
  - url: 'http://host.containers.internal:9090/api/v1/write'