global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.containers.internal:9100']
    metric_relabel_configs:
      - target_label: machine
        replacement: 'jetson'
    

  - job_name: 'jetson-node'
    static_configs:
      - targets: ['jetson_stats_node_exporter:9100']
    metric_relabel_configs:
      - target_label: machine
        replacement: 'jetson'
      - source_labels: [__name__]
        regex: 'integrated_power_mW'
        target_label: __name__
        replacement: 'consumed_power_raw_milliwatts'

  - job_name: 'container'
    static_configs:
      - targets: ['container-stats:9882']
    metric_relabel_configs:
      - target_label: machine
        replacement: 'jetson'

remote_write:
  - url: 'http://host.containers.internal:9090/api/v1/write'