global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.containers.internal:9100']
  
  - job_name: ollama
    static_configs:
      - targets: ['ollama-stats:9882']

  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
