stacks:
  jetson_ollama_gemma3_12b_temp0:
    machine: jetson
    runtime: ollama
    model_name: "gemma3_12b"
    model_path: "gemma3:12b"
    temp: 0.0
    gpu: true
  jetson_ollama_gemma3_12b_temp1: 
    machine: jetson
    runtime: ollama
    model_name: "gemma3_12b"
    model_path: "gemma3:12b"
    temp: 1.0
    gpu: true
