stacks:
  stack1:
      machine: jetson
      runtime: ollama
      model_name: "gemma3_4b"
      model_path: "gemma3:4b"
      temp: 0.0
      gpu: true
  stack2: 
      machine: jetson
      runtime: vllm
      model_name: "granite-vision-3.2-2b"
      model_path: "ibm-granite/granite-vision-3.2-2b"
      temp: 1.0
      gpu: true
