stacks:
  stack1:
    machine: jetson
    runtime: vllm
    model_name: "granite-vision-3.2"
    model_path: "ibm-granite/granite-vision-3.2-2b"
    temp: 0.0
    gpu: true
  stack2: 
    machine: jetson
    runtime: vllm
    model_name: "gemma3_12b"
    model_path: "google/gemma-3-12b-it"
    temp: 0.0
    gpu: true
