services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    ports:
      - "3000:3000"

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.promlocal
    container_name: prometheus
    restart: unless-stopped
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml
      #- prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"

  webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:

      - "OPENAI_API_BASE_URL=http://host.containers.internal:11440/v1"

    container_name: webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  open-webui: {}
